### PR TITLE
Added a controller to handle shortlinks

### PR DESCRIPTION
**Pull request by Spomsoree**

### CODE REVIEW

**Comment by bobdenotter** [comment]
@Spomsoree Hi, why did you close this? I think this is a feature people would like to have.

**Comment by Spomsoree** [comment]
It's not done yet. I've been too tired yesterday, I meant to create a PR in your Fork.

I'll create one if the PR is thought the review of my team.

**Comment by bobdenotter** [comment]
@Spomsoree Ok, cool! :-)

**Comment by Spomsoree** [comment]
We have a router match problem, that you could possibly help.

We'd like to create shortlink routes without any prefix, for example `/b` as a shortlink for blogs.
To do this, we have to match all routes like this: `/{shortlink}`.

Is there a way to continue the router to find matches if our controller doesn't find any shortlink matches?
Otherwise the router would always try to find a page with the given slug.

**Pull request closed without merging**
